permalink: /:year/:month/:day/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

markdown: kramdown

title : Lixiaofei's Blog
author :
  name : Lixiaofei
  email : lixiaofei3910@163.com
  github : lixiaofei3910


production_url : http://linusp.github.io

nav:
  - text: 分类
    url : /categories.html
  - text: 标签
    url : /tags.html
  - text: 存档
    url : /archive.html
  - text: IF
    url : /if.html
  - text: 链接
    url : /link.html
  - text: 关于
    url : /about.html

JB :
  version : 0.3.0

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
